import { createWorkItemAttachment, MAX_ATTACHMENT_SIZE_BYTES } from './feature';
import { AzureDevOpsError } from '../../../shared/errors';
import * as fs from 'fs';

// Mock the fs module
jest.mock('fs');
const mockedFs = jest.mocked(fs);

// Unit tests should only focus on isolated logic
// No real connections, HTTP requests, or dependencies
describe('createWorkItemAttachment unit', () => {
  beforeEach(() => {
    // Reset all mocks before each test
    jest.clearAllMocks();
  });

  // Test for required source validation
  test('should throw error when neither filePath nor content is provided', async () => {
    // Arrange - mock connection, never used due to validation error
    const mockConnection: any = {
      getWorkItemTrackingApi: jest.fn(),
    };

    // Act & Assert
    await expect(
      createWorkItemAttachment(mockConnection, 123, {
        filePath: '', // Empty file path
      }),
    ).rejects.toThrow('Either filePath or content is required');
  });

  test('should throw error when both filePath and content are provided', async () => {
    const mockConnection: any = {
      getWorkItemTrackingApi: jest.fn(),
    };

    await expect(
      createWorkItemAttachment(mockConnection, 123, {
        filePath: '/path/to/file.txt',
        content: Buffer.from('test').toString('base64'),
        fileName: 'file.txt',
      }),
    ).rejects.toThrow('Provide either filePath or content, not both');
  });

  test('should throw error when content is provided without fileName', async () => {
    const mockConnection: any = {
      getWorkItemTrackingApi: jest.fn(),
    };

    await expect(
      createWorkItemAttachment(mockConnection, 123, {
        content: Buffer.from('test').toString('base64'),
      }),
    ).rejects.toThrow('fileName is required when content is provided');
  });

  test('should throw error when attachment exceeds the size limit', async () => {
    // Arrange - mock a file larger than the limit
    mockedFs.existsSync.mockReturnValue(true);
    mockedFs.readFileSync.mockReturnValue(
      Buffer.alloc(MAX_ATTACHMENT_SIZE_BYTES + 1),
    );

    const mockConnection: any = {
      getWorkItemTrackingApi: jest.fn(),
    };

    // Act & Assert
    await expect(
      createWorkItemAttachment(mockConnection, 123, {
        filePath: '/path/to/huge-file.bin',
      }),
    ).rejects.toThrow(/Attachment is too large/);
  });

  test('should upload base64 content and attach it to the work item', async () => {
    // Arrange
    const mockAttachmentUrl =
      'https://dev.azure.com/org/_apis/wit/attachments/abc-123';
    const mockCreateAttachment = jest
      .fn()
      .mockResolvedValue({ id: 'abc-123', url: mockAttachmentUrl });
    const mockUpdateWorkItem = jest
      .fn()
      .mockResolvedValue({ id: 123, relations: [] });

    const mockConnection: any = {
      getWorkItemTrackingApi: jest.fn().mockResolvedValue({
        createAttachment: mockCreateAttachment,
        updateWorkItem: mockUpdateWorkItem,
      }),
    };

    // Act
    const result = await createWorkItemAttachment(mockConnection, 123, {
      content: Buffer.from('generated report').toString('base64'),
      fileName: 'report.txt',
      comment: 'Generated by automation',
    });

    // Assert
    expect(result).toEqual({ id: 123, relations: [] });
    expect(mockCreateAttachment).toHaveBeenCalledWith(
      {},
      expect.anything(),
      'report.txt',
      undefined,
      undefined,
    );
    // The relation patch should reference the uploaded attachment
    expect(mockUpdateWorkItem).toHaveBeenCalledWith(
      {},
      [
        {
          op: 'add',
          path: '/relations/-',
          value: {
            rel: 'AttachedFile',
            url: mockAttachmentUrl,
            attributes: {
              name: 'report.txt',
              comment: 'Generated by automation',
            },
          },
        },
      ],
      123,
      undefined,
      false,
      false,
      false,
      expect.anything(),
    );
    // No filesystem access for base64 content
    expect(mockedFs.readFileSync).not.toHaveBeenCalled();
  });

  // Test for file existence validation
  test('should throw error when file does not exist', async () => {
    // Arrange - mock file does not exist
    mockedFs.existsSync.mockReturnValue(false);

    const mockConnection: any = {
      getWorkItemTrackingApi: jest.fn(),
    };

    // Act & Assert
    await expect(
      createWorkItemAttachment(mockConnection, 123, {
        filePath: '/path/to/nonexistent/file.txt',
      }),
    ).rejects.toThrow('File does not exist: /path/to/nonexistent/file.txt');
  });

  // Test for error propagation
  test('should propagate custom errors when thrown internally', async () => {
    // Arrange - mock file exists
    mockedFs.existsSync.mockReturnValue(true);
    mockedFs.readFileSync.mockReturnValue(Buffer.from('test content'));

    const mockConnection: any = {
      getWorkItemTrackingApi: jest.fn().mockImplementation(() => {
        throw new AzureDevOpsError('Custom error');
      }),
    };

    // Act & Assert
    await expect(
      createWorkItemAttachment(mockConnection, 123, {
        filePath: '/path/to/file.txt',
      }),
    ).rejects.toThrow(AzureDevOpsError);

    await expect(
      createWorkItemAttachment(mockConnection, 123, {
        filePath: '/path/to/file.txt',
      }),
    ).rejects.toThrow('Custom error');
  });

  test('should wrap unexpected errors in a friendly error message', async () => {
    // Arrange - mock file exists
    mockedFs.existsSync.mockReturnValue(true);
    mockedFs.readFileSync.mockReturnValue(Buffer.from('test content'));

    const mockConnection: any = {
      getWorkItemTrackingApi: jest.fn().mockImplementation(() => {
        throw new Error('Unexpected error');
      }),
    };

    // Act & Assert
    await expect(
      createWorkItemAttachment(mockConnection, 123, {
        filePath: '/path/to/file.txt',
      }),
    ).rejects.toThrow('Failed to create attachment: Unexpected error');
  });
});
